sudo: required

language: python
python:
  # We don't actually use the Travis Python (since we are on conda), but this keeps it organized.
  - "3.6"

before_install:
  - export PACKAGE_NAME=test_travis
  # Get and install anaconda (https://conda.io/docs/travis.html)
  - wget -nv https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a  # Useful for debugging any issues with conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no

install:
  - echo "1" > installed
  - conda config --add channels defaults --add channels vladsaveliev --add channels bioconda --add channels conda-forge
  - conda install -q python=$TRAVIS_PYTHON_VERSION pip requests conda-build jinja2 anaconda-client ngs_utils
  # Building package
  - conda build deploy/conda_package/${PACKAGE_NAME}
  - conda install --use-local ${PACKAGE_NAME}


script:
  - cat installed > tested

#deploy:
#  # Deploy to Anaconda.org
#  - provider: script
#    script: ./deploy/deploy_anaconda.sh $PACKAGE_NAME $ANACONDA_TOKEN
#    on:
#      tags: true
#    skip_cleanup: true


deploy:
  # Deploy to Anaconda.org
  - provider: script
    script: rm -rf $HOME/miniconda &&
            docker build -t vladsaveliev/test_travis:$TRAVIS_TAG -f Dockerfile . &&
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin &&
            docker push vladsaveliev/test_travis:$TRAVIS_TAG
    on:
      tags: true
    skip_cleanup: true

##########################
## Pushing to DockerHub
##########################

#after_success:
#  # Building docker image
#  - echo $TRAVIS_BRANCH
#  - test $TRAVIS_BRANCH = "master" && grep -qv dev VERSION.txt &&
#    docker version &&
#    rm -rf $HOME/miniconda umccrise_test_data  &&
#    docker build -t vladsaveliev/test_travis:$(cat VERSION.txt) -f Dockerfile .
#  # Pushing docker image
#  - test $TRAVIS_BRANCH = "master" && grep -qv dev VERSION.txt &&
#    docker images &&
#    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin &&
#    docker push vladsaveliev/test_travis:$(cat VERSION.txt)


##########################
## Job stages
##########################

# stages:
#   - install
#   - test
#   - deploy
 # jobs:
#   include:
#     - stage: install
#       script:
#       - echo "1" > installed
#     - stage: test
#       script:
#       - cat installed > tested
#     - stage: deploy
#       script:
#       - docker version
#       - docker images
#       - cat tested > deployed
