sudo: required 
dist: trusty

language: python
python:
  # We don't actually use the Travis Python (since we are on conda), but this keeps it organized.
  - "3.6"

install:
  - touch installed

script:
  - touch tested

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

after_success:
  - docker version
  - docker images

