sudo: required 
dist: trusty

language: python
python:
  # We don't actually use the Travis Python (since we are on conda), but this keeps it organized.
  - "3.6"

install: true

stages:
  - install
  - test
  - deploy

jobs:
  include:
    - stage: install
      script:
      - echo "1" > installed
    - stage: test
      script:
      - cat installed > tested
    - stage: deploy
      script:
      - docker version
      - docker images
      - cat tested > deployed

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

