{% set data=load_setup_py_data() %}

package:
  name: test_ci
  version: {{ data['version'] }}

source:
  path: ../../

build:
  number: 0
#  noarch: python

requirements:
  build:
    - python {{ python }}
    {% for dep in data.get("install_requires", []) -%}
    - {{ dep.lower() }}
    {% endfor %}
    - pysam
  run:
    - python
    {% for dep in data.get("install_requires", []) -%}
    - {{ dep.lower() }}
    {% endfor %}
    - pysam

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
