name: Build conda package, test and upload to anaconda
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh --no-verbose -O miniconda.sh
          bash miniconda.sh -b
          export PATH="${HOME}/miniconda3/bin:${PATH}"
          conda config --set always_yes yes --set changeps1 no
          conda install -c conda-forge mamba
          mamba update conda
          conda config --add channels defaults --add channels vladsaveliev --add channels bioconda --add channels conda-forge
          cat $HOME/.condarc
          mamba install -c vladsaveliev "python==3.7.*" pip versionpy conda-build conda-verify anaconda-client

      - name: Build package
        run: |
          export PATH="${HOME}/miniconda3/bin:${PATH}"
          cat $HOME/.condarc
          mamba build conda/test_travis --output-folder conda/test_travis

      - name: Install and test
        run: |
          export PATH="${HOME}/miniconda3/bin:${PATH}"
          cd conda/test_travis
          mamba install --use-local test_travis

      - name: Upload to anaconda
        run: |
          export PATH="${HOME}/miniconda3/bin:${PATH}"
          cd conda/test_travis
          mamba convert -p osx-64 linux-64/*.tar.bz2
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload linux-64/*.tar.bz2
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload osx-64/*.tar.bz2


