name: Build conda package, test and upload to anaconda
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: setup
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh --no-verbose -O miniconda.sh
          bash miniconda.sh -b
          export PATH="${PWD}/miniconda3/bin:${PATH}"
          conda config --set always_yes yes --set changeps1 no
          conda install -c conda-forge mamba
          echo $PATH
          ls ${PWD}/miniconda3/bin
          ${PWD}/miniconda3/bin/mamba update conda
          mamba update conda


